name: codime
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera:
  path_provider:
  path:
  image_picker:
  weight_slider: ^1.2.0
  height_slider: ^1.3.1
  tabbar: ^0.1.1
  flutter_snake_navigationbar: ^0.4.4
  dataclass: ^0.5.0+1
  circle_button: ^1.0.1
  syncfusion_flutter_sliders: ^18.4.42-beta
  http: ^0.12.2
  drag_to_expand: ^0.0.1
  sqflite:
  animated_splash_screen: ^1.0.1+2
  image: ^2.1.19
  smooth_page_indicator: ^0.2.0
  speech_bubble: ^0.0.7
  url_launcher: ^5.7.10
  flutter_easyloading: ^2.2.2
  image_size_getter: ^0.2.1
  kakao_flutter_sdk: ^0.5.4
  flutter_bloc: ^0.20.0
  cupertino_icons: ^1.0.0
  settings_ui: ^0.6.0
  dio: ^3.0.10
  image_gallery_saver: '^1.6.8'
  permission_handler: ^5.1.0+2
  fluttertoast: ^7.1.8
  gender_picker: ^1.0.2
  shared_preferences: ^0.5.7
  multi_image_picker: ^4.7.15
  number_selection: ^0.0.1
  image_crop: ^0.3.4
  infinite_scroll_pagination: ^2.3.0
  cached_network_image: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
    - assets/applogo.png
    - assets/hanger.png
    - assets/storage.png
    - assets/wall_texture.png
    - assets/hanger_hook.png
    - assets/email.png
    - assets/mailbox.png
    - assets/blackboard.png
    - assets/images/
    - assets/request_codi/
    - assets/mainfeed_person/
  fonts:
    - family: NotoSans
      fonts:
        - asset: fonts/NotoSans-Regular.ttf
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf
    - family: GamjaFlower
      fonts:
        - asset: fonts/GamjaFlower-Regular.ttf
    - family: GreatVibes
      fonts:
        - asset: fonts/GreatVibes-Regular.ttf
